create table t_quality_manager(
id int auto_increment primary key,
wId int not null comment '仓号ID',
grainVariety varchar(32) comment '粮食品种',
grainProperty varchar(32) comment '粮食性质',
currentWeight float comment '当前重量',
checkDate datetime comment '检测日期',
rz float  comment '容重出糙',
sf float comment '水分',
zz float comment '杂质',
kwz float comment '矿物质',
bwsld float comment '不完善粒度',
zjml float comment '整精米粒',
gwcm float comment '谷外糙米',
hlm float comment '黄粒米',
hh float comment '互混',
cmbl float comment '赤霉病粒',
ydzs float comment '硬度指数',
szqw varchar(16) comment '色泽气味',
level char(2) comment '等级',
qualityType char(1) comment '质检类型：1-出库，2-入库，3-平仓',
buyYear char(4) comment '收获年度',
version int NOT NULL DEFAULT '1',
dataOperator int comment '数据操作员'
)comment '质量检测';


create table t_quality_manager_his(
id int,
wId int not null comment '仓号ID',
grainVariety varchar(32) comment '粮食品种',
grainProperty varchar(32) comment '粮食性质',
currentWeight float comment '当前重量',
checkDate datetime comment '检测日期',
rz float  comment '容重出糙',
sf float comment '水分',
zz float comment '杂质',
kwz float comment '矿物质',
bwsld float comment '不完善粒度',
zjml float comment '整精米粒',
gwcm float comment '谷外糙米',
hlm float comment '黄粒米',
hh float comment '互混',
cmbl float comment '赤霉病粒',
ydzs float comment '硬度指数',
szqw varchar(16) comment '色泽气味',
level char(2) comment '等级',
qualityType char(1) comment '质检类型：1-出库，2-入库，3-平仓',
buyYear char(4) comment '收获年度',
version int NOT NULL DEFAULT '1',
dataOperator int comment '数据操作员',

execUser int comment '操作者',
execSQL text comment '操作语句',
execType varchar(16) comment '操作类型',
execDate timestamp null default CURRENT_TIMESTAMP comment '操作时间'
)comment '质量检测操作历史';