
package com.ictehi.grainplat.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import grainplat.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GrainplatServicePortType", targetNamespace = "http://service.grainplat.ictehi.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GrainplatServicePortType {


    /**
     * 
     * @param args3
     * @param args4
     * @param args1
     * @param args2
     * @param args0
     * @return
     *     returns int
     */
    @WebMethod(action = "urn:saveOrUpdateGrainDepotInfo")
    @WebResult(targetNamespace = "http://grainplat")
    @RequestWrapper(localName = "saveOrUpdateGrainDepotInfo", targetNamespace = "http://grainplat", className = "grainplat.SaveOrUpdateGrainDepotInfo")
    @ResponseWrapper(localName = "saveOrUpdateGrainDepotInfoResponse", targetNamespace = "http://grainplat", className = "grainplat.SaveOrUpdateGrainDepotInfoResponse")
    public int saveOrUpdateGrainDepotInfo(
        @WebParam(name = "args0", targetNamespace = "http://grainplat")
        String args0,
        @WebParam(name = "args1", targetNamespace = "http://grainplat")
        String args1,
        @WebParam(name = "args2", targetNamespace = "http://grainplat")
        int args2,
        @WebParam(name = "args3", targetNamespace = "http://grainplat")
        String args3,
        @WebParam(name = "args4", targetNamespace = "http://grainplat")
        String args4);

}
