
package com.ictehi.grainplat.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GrainplatService", targetNamespace = "http://service.grainplat.ictehi.com", wsdlLocation = "http://58.221.129.162:9090/grainplat/services/GrainplatService?wsdl")
public class GrainplatService
    extends Service
{

    private final static URL GRAINPLATSERVICE_WSDL_LOCATION;
    private final static WebServiceException GRAINPLATSERVICE_EXCEPTION;
    private final static QName GRAINPLATSERVICE_QNAME = new QName("http://service.grainplat.ictehi.com", "GrainplatService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://58.221.129.162:9090/grainplat/services/GrainplatService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GRAINPLATSERVICE_WSDL_LOCATION = url;
        GRAINPLATSERVICE_EXCEPTION = e;
    }

    public GrainplatService() {
        super(__getWsdlLocation(), GRAINPLATSERVICE_QNAME);
    }

    public GrainplatService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GRAINPLATSERVICE_QNAME, features);
    }

    public GrainplatService(URL wsdlLocation) {
        super(wsdlLocation, GRAINPLATSERVICE_QNAME);
    }

    public GrainplatService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GRAINPLATSERVICE_QNAME, features);
    }

    public GrainplatService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GrainplatService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GrainplatServicePortType
     */
    @WebEndpoint(name = "GrainplatServiceHttpSoap11Endpoint")
    public GrainplatServicePortType getGrainplatServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.grainplat.ictehi.com", "GrainplatServiceHttpSoap11Endpoint"), GrainplatServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GrainplatServicePortType
     */
    @WebEndpoint(name = "GrainplatServiceHttpSoap11Endpoint")
    public GrainplatServicePortType getGrainplatServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.grainplat.ictehi.com", "GrainplatServiceHttpSoap11Endpoint"), GrainplatServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GRAINPLATSERVICE_EXCEPTION!= null) {
            throw GRAINPLATSERVICE_EXCEPTION;
        }
        return GRAINPLATSERVICE_WSDL_LOCATION;
    }

}
