
package com.aisino.grain.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.aisino.grain.webservice.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GrainService", targetNamespace = "http://webservice.grain.aisino.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GrainService {


    /**
     * 
     * @param dataType
     * @param orgCode
     * @param checkData
     * @param entCode
     * @param jsonData
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrUpdateGrainDepotInfo", targetNamespace = "http://webservice.grain.aisino.com/", className = "com.aisino.grain.webservice.SaveOrUpdateGrainDepotInfo")
    @ResponseWrapper(localName = "saveOrUpdateGrainDepotInfoResponse", targetNamespace = "http://webservice.grain.aisino.com/", className = "com.aisino.grain.webservice.SaveOrUpdateGrainDepotInfoResponse")
    @Action(input = "http://webservice.grain.aisino.com/GrainService/saveOrUpdateGrainDepotInfoRequest", output = "http://webservice.grain.aisino.com/GrainService/saveOrUpdateGrainDepotInfoResponse")
    public int saveOrUpdateGrainDepotInfo(
        @WebParam(name = "jsonData", targetNamespace = "")
        byte[] jsonData,
        @WebParam(name = "checkData", targetNamespace = "")
        String checkData,
        @WebParam(name = "dataType", targetNamespace = "")
        int dataType,
        @WebParam(name = "orgCode", targetNamespace = "")
        String orgCode,
        @WebParam(name = "entCode", targetNamespace = "")
        String entCode);

}
