
package com.aisino.grain.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GrainServiceImplService", targetNamespace = "http://impl.webservice.grain.aisino.com/", wsdlLocation = "http://58.213.152.55:8082/grainplatform-webservice/jeecg?wsdl")
public class GrainServiceImplService
    extends Service
{

    private final static URL GRAINSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GRAINSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GRAINSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.grain.aisino.com/", "GrainServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://58.213.152.55:8082/grainplatform-webservice/jeecg?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GRAINSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GRAINSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GrainServiceImplService() {
        super(__getWsdlLocation(), GRAINSERVICEIMPLSERVICE_QNAME);
    }

    public GrainServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GRAINSERVICEIMPLSERVICE_QNAME, features);
    }

    public GrainServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GRAINSERVICEIMPLSERVICE_QNAME);
    }

    public GrainServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GRAINSERVICEIMPLSERVICE_QNAME, features);
    }

    public GrainServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GrainServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GrainService
     */
    @WebEndpoint(name = "GrainServiceImplPort")
    public GrainService getGrainServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.grain.aisino.com/", "GrainServiceImplPort"), GrainService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GrainService
     */
    @WebEndpoint(name = "GrainServiceImplPort")
    public GrainService getGrainServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.grain.aisino.com/", "GrainServiceImplPort"), GrainService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GRAINSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GRAINSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GRAINSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
